---
- name: Create groups
  group:
    name={{ item.groupname }}
    state={{ item.state }}
  with_items:
    - "{{ ds_groups }}"

- name: Create users
  user:
    comment={{ item.comment }}
    name={{ item.user }}
    state={{ item.state }}
    groups={{ item.group }}
  with_items:
    - "{{ ds_users }}"

- authorized_key:
    user={{ item.user }}
    key={{ lookup('file', item.user+'.pub') }}
  with_items:
    - "{{ ds_users }}"

- name: Assign appropriate permissions
  file:
    path: "/home/{{ item.user }}"
    mode: 0750
  with_items: "{{ ds_users }}"
